application:
  name: 'contest-backend'
  project: 'contest-backend'
  organization: 'QoveryCommunity'
  publicly_accessible: true
routers:
  - name: 'main-contest-backend'
    routes:
      - application_name: 'contest-backend'
        paths:
          - '/*'
