FROM node:14-alpine

RUN mkdir -p /usr/src/xxx
WORKDIR /usr/src/xxx

RUN apk update && apk upgrade

ARG CLOUDINARY_CLOUD_NAME
ENV CLOUDINARY_CLOUD_NAME = $ARG CLOUDINARY_CLOUD_NAME

ARG CLOUDINARY_SECRET
ENV CLOUDINARY_SECRET = $ARG CLOUDINARY_SECRET

ARG CLOUDINARY_KEY
ENV CLOUDINARY_KEY = $ARG CLOUDINARY_KEY

ARG DATABASE_URL
ENV DATABASE_URL = $ARG DATABASE_URL

ARG SESSION_SECRET
ENV SESSION_SECRET = $ARG SESSION_SECRET


COPY ./backend /usr/src/xxx/

RUN yarn install
RUN yarn build

EXPOSE 3000
# start the app
CMD [ "yarn", "start" ]